import type { NodeDefinition, NodeKind } from "../types";
import {
  assetImageModule,
  assetTextModule,
  researchModule,
  webpageModule,
} from "./context";
import { transcriptionModule } from "./ai";

export const BRAND_ARTIFACTS = {
  brief: "flowz.brand-brief",
  audience: "flowz.audience-analysis",
  names: "flowz.name-candidate-list",
  domains: "flowz.domain-availability",
  handles: "flowz.handle-plan",
  fonts: "flowz.font-pairing",
  palette: "flowz.color-palette",
  artboard: "flowz.artboard-reference",
} as const;

function portType(port: {
  valueType: { kind: string; scalar?: string; item?: string };
}) {
  const value =
    port.valueType.kind === "scalar"
      ? port.valueType.scalar
      : port.valueType.item;
  return value === "image"
    ? ("image" as const)
    : value === "text"
      ? ("text" as const)
      : ("list" as const);
}

function contextDefinition(
  kind: NodeKind,
  module:
    | typeof webpageModule
    | typeof researchModule
    | typeof assetTextModule
    | typeof assetImageModule,
  description: string,
): NodeDefinition {
  return {
    kind,
    label: module.label,
    description,
    category: "Kontext",
    inputs: module.inputs.map((input) => ({
      id: input.id,
      label: input.label,
      type: portType(input),
      optional: input.optional,
      multiple: input.cardinality === "many",
    })),
    outputs: module.outputs.map((output) => ({
      id: output.id,
      label: output.label,
      type: portType(output),
    })),
    defaults: module.defaultConfig,
  };
}

/**
 * Product specification data shared by concrete node modules. This file owns
 * no rendering or execution dispatch.
 */
export const nodeSpecifications: Record<NodeKind, NodeDefinition> = {
  unsupported: {
    kind: "unsupported",
    label: "Nicht unterstützter Node",
    description: "Modul ist in dieser FlowZ-Version nicht verfügbar",
    category: "System",
    inputs: [],
    outputs: [],
    defaults: {},
  },
  textInput: {
    kind: "textInput",
    label: "Text-Eingabe",
    description: "Prompt oder Kontext",
    category: "Eingabe",
    inputs: [],
    outputs: [{ id: "text", label: "Text", type: "text" }],
    defaults: {
      value:
        "Beschreibe eine futuristische Kamera als hochwertiges Produktfoto.",
    },
  },
  imageInput: {
    kind: "imageInput",
    label: "Bild-Import",
    description: "Lokale Referenz",
    category: "Eingabe",
    inputs: [],
    outputs: [{ id: "image", label: "Bild", type: "image" }],
    defaults: {},
  },
  videoInput: {
    kind: "videoInput",
    label: "Video-Import",
    description: "Lokalen Clip sicher importieren",
    category: "Eingabe",
    inputs: [],
    outputs: [
      { id: "video", label: "Video", type: "video" },
      { id: "startFrame", label: "Startbild", type: "image" },
      { id: "endFrame", label: "Endbild", type: "image" },
    ],
    defaults: {},
  },
  audioInput: {
    kind: "audioInput",
    label: "Audio-Import",
    description: "Aufnahme oder Audiodatei importieren",
    category: "Eingabe",
    inputs: [],
    outputs: [{ id: "audio", label: "Audio", type: "audio" }],
    defaults: {},
  },
  imageCollection: {
    kind: "imageCollection",
    label: "Bildauswahl",
    description: "Unveränderliche kuratierte Bildliste",
    category: "Eingabe",
    inputs: [],
    outputs: [{ id: "images", label: "Bildliste", type: "imageList" }],
    defaults: {},
    hidden: true,
  },
  videoCollection: {
    kind: "videoCollection",
    label: "Videoauswahl",
    description: "Unveränderliche kuratierte Videoliste",
    category: "Eingabe",
    inputs: [],
    outputs: [{ id: "videos", label: "Videoliste", type: "videoList" }],
    defaults: {},
    hidden: true,
  },
  assetText: {
    ...contextDefinition(
      "assetText",
      assetTextModule,
      "Schreibgeschützte globale Asset-Version",
    ),
    category: "Eingabe",
    hidden: true,
  },
  assetImage: {
    ...contextDefinition(
      "assetImage",
      assetImageModule,
      "Schreibgeschützte globale Asset-Version",
    ),
    category: "Eingabe",
    hidden: true,
  },
  textGeneration: {
    kind: "textGeneration",
    label: "Textgenerierung",
    description: "Text mit KI erzeugen",
    category: "Modell",
    inputs: [
      { id: "prompt", label: "Text", type: "text", multiple: true },
      {
        id: "textLists",
        label: "Varianten",
        type: "textList",
        optional: true,
        multiple: true,
      },
    ],
    outputs: [
      { id: "text", label: "Text", type: "text" },
      { id: "texts", label: "Alle Varianten", type: "textList" },
    ],
    defaults: {
      model: "google/gemini-3.5-flash",
      prompt: "Antworte prägnant auf Deutsch.",
      outputMode: "single",
      variantCount: 1,
      listProcessingMode: "aggregate",
    },
  },
  imageGeneration: {
    kind: "imageGeneration",
    label: "Bildgenerierung",
    description: "Text zu Bild",
    category: "Modell",
    inputs: [
      { id: "prompt", label: "Text", type: "text", multiple: true },
      {
        id: "reference",
        label: "Bild",
        type: "image",
        optional: true,
        multiple: true,
      },
      {
        id: "referenceLists",
        label: "Bildliste",
        type: "imageList",
        optional: true,
        multiple: true,
      },
      { id: "mask", label: "Maske", type: "image", optional: true },
    ],
    outputs: [
      { id: "image", label: "Bild", type: "image" },
      { id: "images", label: "Bildliste", type: "imageList" },
    ],
    defaults: {
      model: "google/nano-banana-2-lite",
      prompt: "Fotorealistisch, präzises Studiolicht.",
      aspectRatio: "1:1",
      resolution: "1K",
      outputFormat: "png",
      variants: 1,
      safetyTolerance: "6",
      imageEndpointConfigs: {},
    },
  },
  imageUpscale: {
    kind: "imageUpscale",
    label: "Bild hochskalieren",
    description: "Auflösung mit fal.ai erhöhen",
    category: "Modell",
    inputs: [{ id: "image", label: "Bild", type: "image" }],
    outputs: [{ id: "image", label: "Bild", type: "image" }],
    defaults: {
      model: "fal-ai/seedvr/upscale/image",
      upscaleMode: "factor",
      factor: 2,
      targetResolution: "1080p",
      outputFormat: "png",
      noise: 0.1,
      topazModel: "Standard V2",
      faceEnhancement: false,
      subjectDetection: "All",
      faceEnhancementCreativity: 0,
      faceEnhancementStrength: 0.8,
      sharpen: 0,
      denoise: 0,
      fixCompression: 0,
      strength: 0.5,
      creativity: 1,
      texture: 1,
      redefinePrompt: "",
      autoprompt: true,
      detail: 0.5,
      premiumConfirmed: false,
      cropToFill: false,
    },
  },
  imageTransform: {
    kind: "imageTransform",
    label: "Bild zuschneiden / skalieren",
    description: "Lokal, präzise und kostenlos",
    category: "Kontext",
    inputs: [
      { id: "image", label: "Bild", type: "image" },
      {
        id: "imageLists",
        label: "Bildliste",
        type: "imageList",
        optional: true,
      },
    ],
    outputs: [
      { id: "image", label: "Bild", type: "image" },
      { id: "images", label: "Bildliste", type: "imageList" },
    ],
    defaults: {
      transformMode: "fit",
      transformAspect: "original",
      targetWidth: 1024,
      targetHeight: 1024,
      dimensionLock: true,
      noUpscale: true,
      outputFormat: "png",
      transformQuality: 90,
      transformBackground: "#ffffff",
      cropX: 0,
      cropY: 0,
      cropWidth: 1,
      cropHeight: 1,
      listProcessingMode: "map",
    },
  },
  imageTrimTransparent: {
    kind: "imageTrimTransparent", label: "Transparenz beschneiden", description: "Leeren transparenten Rand lokal entfernen", category: "Kontext",
    inputs: [{ id: "image", label: "Bild", type: "image" }, { id: "imageLists", label: "Bildliste", type: "imageList", optional: true }],
    outputs: [{ id: "image", label: "Bild", type: "image" }, { id: "images", label: "Bildliste", type: "imageList" }],
    defaults: { trimPadding: 2, trimThreshold: 0, listProcessingMode: "map" },
  },
  backgroundRemoval: {
    kind: "backgroundRemoval",
    label: "Hintergrund entfernen",
    description: "Bild mit Bria transparent freistellen",
    category: "Modell",
    inputs: [{ id: "image", label: "Bild", type: "image" }],
    outputs: [{ id: "image", label: "Bild", type: "image" }],
    defaults: { model: "fal-ai/bria/background/remove" },
  },
  videoGeneration: {
    kind: "videoGeneration",
    label: "Videogenerierung",
    description: "Text und Bilder zu Video mit fal.ai",
    category: "Modell",
    inputs: [
      { id: "prompt", label: "Text", type: "text", multiple: true },
      { id: "startFrame", label: "Startbild", type: "image", optional: true },
      { id: "endFrame", label: "Endbild", type: "image", optional: true },
      {
        id: "references",
        label: "Bild",
        type: "image",
        optional: true,
        multiple: true,
      },
      {
        id: "referenceLists",
        label: "Bildliste",
        type: "imageList",
        optional: true,
        multiple: true,
      },
    ],
    outputs: [
      { id: "video", label: "Video", type: "video" },
      { id: "videos", label: "Videoliste", type: "videoList" },
      { id: "startFrame", label: "Startbild", type: "image" },
      { id: "endFrame", label: "Endbild", type: "image" },
    ],
    defaults: {
      model: "bytedance/seedance-2.0/fast/text-to-video",
      prompt: "",
      duration: "auto",
      resolution: "480p",
      aspectRatio: "16:9",
      generateAudio: true,
      bitrateMode: "standard",
      variantCount: 1,
      listProcessingMode: "aggregate",
      endpointConfigs: {},
    },
  },
  videoFrame: {
    kind: "videoFrame",
    label: "Frame aus Video",
    description: "Ersten, letzten oder beliebigen Frame extrahieren",
    category: "Kontext",
    inputs: [{ id: "video", label: "Video", type: "video" }],
    outputs: [{ id: "image", label: "Bild", type: "image" }],
    defaults: { frameMode: "last", frameValue: 50 },
  },
  imageAnalysis: {
    kind: "imageAnalysis",
    label: "Bildanalyse",
    description: "Bild verstehen",
    category: "Modell",
    inputs: [
      { id: "image", label: "Bild", type: "image", multiple: true },
      {
        id: "imageLists",
        label: "Bildliste",
        type: "imageList",
        optional: true,
        multiple: true,
      },
      {
        id: "question",
        label: "Text",
        type: "text",
        optional: true,
        multiple: true,
      },
    ],
    outputs: [
      { id: "text", label: "Text", type: "text" },
      { id: "texts", label: "Alle Varianten", type: "textList" },
    ],
    defaults: {
      model: "openai/gpt-4o-mini",
      prompt: "Beschreibe Motiv, Komposition, Licht und Stil dieses Bildes.",
      variantCount: 1,
      listProcessingMode: "aggregate",
    },
  },
  transcription: {
    kind: "transcription",
    label: transcriptionModule.label,
    description: "Audio präzise in Text umwandeln",
    category: "Modell",
    inputs: [{ id: "audio", label: "Audio", type: "audio" }],
    outputs: [{ id: "text", label: "Text", type: "text" }],
    defaults: transcriptionModule.defaultConfig,
  },
  webpage: contextDefinition(
    "webpage",
    webpageModule,
    "Webseite sicher als Text erfassen",
  ),
  research: contextDefinition(
    "research",
    researchModule,
    "Websuche mit Quellen",
  ),
  brandBrief: {
    kind: "brandBrief",
    label: "Markenbriefing",
    description: "Kompakte, editierbare Markenbasis",
    category: "Marke",
    inputs: [],
    outputs: [{ id: "brief", label: "Briefing", type: "json", artifact: BRAND_ARTIFACTS.brief }],
    defaults: {
      brandName: "",
      offer: "",
      audience: "",
      problem: "",
      promise: "",
      personality: "",
      differentiators: "",
      constraints: "",
    },
  },
  audienceAnalysis: {
    kind: "audienceAnalysis",
    label: "Zielgruppe analysieren",
    description: "Erkenntnisse und Annahmen sauber trennen",
    category: "Marke",
    inputs: [
      { id: "brief", label: "Briefing", type: "json", artifact: BRAND_ARTIFACTS.brief },
      {
        id: "research",
        label: "Recherche",
        type: "text",
        optional: true,
        multiple: true,
      },
    ],
    outputs: [{ id: "audience", label: "Zielgruppe", type: "json", artifact: BRAND_ARTIFACTS.audience }],
    defaults: { model: "google/gemini-3.5-flash", prompt: "" },
  },
  brandNames: {
    kind: "brandNames",
    label: "Markennamen entwickeln",
    description: "Strukturierte Kandidaten mit stabilen IDs",
    category: "Marke",
    inputs: [
      { id: "brief", label: "Briefing", type: "json", artifact: BRAND_ARTIFACTS.brief },
      { id: "audience", label: "Zielgruppe", type: "json", artifact: BRAND_ARTIFACTS.audience, optional: true },
    ],
    outputs: [{ id: "names", label: "Namensartefakt", type: "json", artifact: BRAND_ARTIFACTS.names }],
    defaults: {
      model: "google/gemini-3.5-flash",
      candidateCount: 8,
      iteration: 0,
      prompt: "",
    },
  },
  domainCheck: {
    kind: "domainCheck",
    label: "Domains prüfen",
    description: "Zeitgestempelte IANA-RDAP-Auskunft",
    category: "Marke",
    inputs: [
      {
        id: "names",
        label: "Namensartefakt",
        type: "json",
        artifact: BRAND_ARTIFACTS.names,
        optional: true,
      },
    ],
    outputs: [{ id: "domains", label: "Domainstatus", type: "json", artifact: BRAND_ARTIFACTS.domains }],
    defaults: {
      tlds: [
        "com",
        "de",
        "io",
        "co",
        "ai",
        "app",
        "dev",
        "design",
        "studio",
        "agency",
        "digital",
        "media",
        "tech",
        "tools",
        "software",
        "cloud",
        "xyz",
        "net",
        "org",
        "eu",
      ],
      privacyConsent: false,
      selectedNameId: "",
      domainName: "",
    },
  },
  handlePlan: {
    kind: "handlePlan",
    label: "Handle-Plan",
    description: "Syntax und offizielle manuelle Prüfpfade",
    category: "Marke",
    inputs: [
      { id: "names", label: "Namensartefakt", type: "json", artifact: BRAND_ARTIFACTS.names, optional: true },
    ],
    outputs: [{ id: "handles", label: "Handle-Plan", type: "json", artifact: BRAND_ARTIFACTS.handles }],
    defaults: { handle: "", selectedNameId: "" },
  },
  fontPairing: {
    kind: "fontPairing",
    label: "Font-Pairing",
    description: "Google Fonts mit Quelle und Lizenz",
    category: "Marke",
    inputs: [
      { id: "brief", label: "Briefing", type: "json", artifact: BRAND_ARTIFACTS.brief, optional: true },
      { id: "audience", label: "Zielgruppe", type: "json", artifact: BRAND_ARTIFACTS.audience, optional: true },
    ],
    outputs: [
      { id: "pairing", label: "Typografie", type: "json", artifact: BRAND_ARTIFACTS.fonts },
      { id: "styleHint", label: "Stilhinweis", type: "text" },
    ],
    defaults: {
      model: "google/gemini-3.5-flash",
      fontPresetSeed: 0,
      fontMood: "modern",
      fontSpecimenText: "Klar gedacht. Schön erzählt.",
      headingFont: "Space Grotesk",
      headingFontVariant: 0,
      headingFontAxes: {},
      bodyFont: "Inter",
      bodyFontVariant: 0,
      bodyFontAxes: {},
    },
  },
  colorPalette: {
    kind: "colorPalette",
    label: "Farbpalette",
    description: "Rollenbasierte sRGB-Farben mit WCAG-Kontrast",
    category: "Marke",
    inputs: [
      { id: "brief", label: "Briefing", type: "json", artifact: BRAND_ARTIFACTS.brief },
      { id: "audience", label: "Zielgruppe", type: "json", artifact: BRAND_ARTIFACTS.audience, optional: true },
    ],
    outputs: [{ id: "palette", label: "Farbpalette", type: "json", artifact: BRAND_ARTIFACTS.palette }],
    defaults: { model: "google/gemini-3.5-flash", paletteDirection: "" },
  },
  logoDesign: {
    kind: "logoDesign",
    label: "Logo entwickeln",
    description: "Transparente Logo-Varianten mit fal.ai",
    category: "Marke",
    inputs: [
      { id: "brief", label: "Briefing", type: "json", artifact: BRAND_ARTIFACTS.brief },
      { id: "audience", label: "Zielgruppe", type: "json", artifact: BRAND_ARTIFACTS.audience, optional: true },
      { id: "palette", label: "Farbpalette", type: "json", artifact: BRAND_ARTIFACTS.palette, optional: true },
      {
        id: "references",
        label: "Bild",
        type: "image",
        optional: true,
        multiple: true,
      },
      {
        id: "referenceLists",
        label: "Bildliste",
        type: "imageList",
        optional: true,
        multiple: true,
      },
    ],
    outputs: [
      { id: "image", label: "Logo", type: "image" },
      { id: "images", label: "Logoliste", type: "imageList" },
    ],
    defaults: {
      model: "fal-ai/gpt-image-1.5",
      prompt: "Klar, eigenständig und auch in kleiner Größe erkennbar.",
      inlineBrief: "",
      briefOverride: false,
      resolution: "1024x1024",
      aspectRatio: "auto",
      outputFormat: "png",
      variants: 2,
      quality: "high",
      background: "transparent",
      inputFidelity: "high",
      imageEndpointConfigs: {},
    },
  },
  artboard: {
    kind: "artboard",
    label: "Artboard",
    description: "Editierbare Social-Komposition",
    category: "Marke",
    inputs: [
      { id: "palette", label: "Farbpalette", type: "json", artifact: BRAND_ARTIFACTS.palette, optional: true },
      { id: "fonts", label: "Typografie", type: "json", artifact: BRAND_ARTIFACTS.fonts, optional: true },
      {
        id: "images",
        label: "Bild",
        type: "image",
        optional: true,
        multiple: true,
      },
      {
        id: "imageLists",
        label: "Bildliste",
        type: "imageList",
        optional: true,
        multiple: true,
      },
    ],
    outputs: [
      { id: "artboard", label: "Artboard", type: "json", artifact: BRAND_ARTIFACTS.artboard },
      { id: "image", label: "Aktives Bild", type: "image" },
      { id: "images", label: "Ausgewählte Bilder", type: "imageList" },
    ],
    defaults: { artboardSelectedImageHashes: [] },
  },
};
