import { beforeEach,describe,expect,it,vi } from "vitest";
import { MemoryArtboardProposalRepository } from "./proposal-repository";
import { ARTBOARD_DOCUMENT_VERSION,ARTBOARD_WORKSPACE_VERSION,type ArtboardWorkspace } from "../nodes/brand/artboard-domain";
import { falImageModel,defaultFalImageConfig } from "../nodes/image/capabilities";
import { artboardIntentRequestIdentity,artboardIntentRunId,executeArtboardImageIntent,persistPaidResultProposal,resolveIntentReferences,type ArtboardPaidImageContext } from "./artboard-paid-image";
import { cancelFalImage,completedFalImage,pendingFalImageRuns,resumeFalImage,runFalImage } from "../api";

vi.mock("../api",()=>({cancelFalImage:vi.fn(async()=>true),completedFalImage:vi.fn(async()=>undefined),pendingFalImageRuns:vi.fn(async()=>[]),resumeFalImage:vi.fn(),runFalImage:vi.fn()}));
const hash="a".repeat(64);
const workspace:ArtboardWorkspace={schemaVersion:ARTBOARD_WORKSPACE_VERSION,id:"workspace",name:"Workspace",boards:{board:{id:"board",name:"Board",activeRevisionId:"board-revision",createdAt:"2026-07-12T10:00:00.000Z",ancestry:{branchId:"branch"},inputSnapshot:{id:"snapshot",createdAt:"2026-07-12T10:00:00.000Z",bindings:{}},document:{schemaVersion:ARTBOARD_DOCUMENT_VERSION,id:"document",name:"Board",format:{preset:"instagram-post",width:1080,height:1080},paint:{kind:"solid",color:"#fff"},rootLayerIds:[],layers:{},bindings:{reference:{id:"reference",source:{projectId:"flow",nodeId:"image",portId:"image",resultId:"source-result"},snapshot:{kind:"cas",hash},mode:"pinned"}},tokenRefs:{}}}},placements:{board:{x:0,y:0}},selectedBoardIds:["board"],activeBoardId:"board",pasteboard:{margin:100,gap:100,grid:10}};
const context:ArtboardPaidImageContext={workspace,workspaceId:"workspace",branchId:"branch",revision:{id:"revision-1",number:1},proposalId:"proposal",intent:{id:"intent",provider:"fal.ai",boardId:"board",prompt:"Editorial hero",role:"Hero",aspectRatio:"1:1",referenceBindingIds:["reference"],requiresExplicitConfirmation:true}};
const result={runId:"11111111-1111-5111-8111-111111111111",modelId:"fal-ai/gpt-image-1.5",endpoint:"fal-ai/gpt-image-1.5/edit",images:[{resultId:"result",assetId:"asset",blobHash:hash,mediaType:"image/png",width:1024,height:1024,hasAlpha:true}],costMicrounits:12345,costProvenance:"actual" as const,targetCurrent:false};

describe("artboard paid image intent",()=>{
  beforeEach(()=>vi.clearAllMocks());
  it("resolves only immutable CAS references and derives a stable UUID",async()=>{expect(resolveIntentReferences(context)).toEqual([`flowz-cas:${hash}`]);expect(await artboardIntentRunId(context)).toBe(await artboardIntentRunId(context));});
  it("never submits without the explicit confirmation contract",async()=>{const model=falImageModel("fal-ai/gpt-image-1.5")!;await expect(executeArtboardImageIntent({...context,intent:{...context.intent,requiresExplicitConfirmation:false as true}},model,{...defaultFalImageConfig(model),aspectRatio:"1:1"},new AbortController().signal)).rejects.toThrow(/Bestätigung/);expect(runFalImage).not.toHaveBeenCalled();});
  it("recovers completed and pending runs without a second submit",async()=>{const model=falImageModel("fal-ai/gpt-image-1.5")!,config={...defaultFalImageConfig(model),aspectRatio:"1:1"},runId=await artboardIntentRunId(context,artboardIntentRequestIdentity(context,model,config));vi.mocked(completedFalImage).mockResolvedValueOnce(result);expect(await executeArtboardImageIntent(context,model,config,new AbortController().signal)).toBe(result);expect(runFalImage).not.toHaveBeenCalled();vi.mocked(completedFalImage).mockResolvedValueOnce(undefined);vi.mocked(pendingFalImageRuns).mockResolvedValueOnce([{runId,projectId:"workspace",nodeId:"artboard-intent:intent",modelId:model.id,endpoint:model.editEndpoint!,phase:"queued",createdAt:"now",streaming:false,resumable:true}]);vi.mocked(resumeFalImage).mockResolvedValueOnce(result);await expect(executeArtboardImageIntent(context,model,config,new AbortController().signal)).resolves.toBe(result);expect(runFalImage).not.toHaveBeenCalled();});
  it("binds idempotency to the exact confirmed request, not changing price observations",async()=>{const model=falImageModel("fal-ai/gpt-image-1.5")!,base={...defaultFalImageConfig(model),aspectRatio:"1:1"};const first=await artboardIntentRunId(context,artboardIntentRequestIdentity(context,model,base));expect(first).toBe(await artboardIntentRunId(context,artboardIntentRequestIdentity(context,model,base)));expect(first).not.toBe(await artboardIntentRunId(context,artboardIntentRequestIdentity(context,model,{...base,variants:2})));});
  it("requests provider cancellation and does not resubmit",async()=>{const model=falImageModel("fal-ai/gpt-image-1.5")!,config={...defaultFalImageConfig(model),aspectRatio:"1:1"};let resolve!:(value:typeof result)=>void;vi.mocked(runFalImage).mockReturnValueOnce(new Promise((done)=>{resolve=done;}));const controller=new AbortController(),running=executeArtboardImageIntent(context,model,config,controller.signal);await vi.waitFor(()=>expect(runFalImage).toHaveBeenCalledTimes(1));controller.abort();resolve(result);await running;expect(cancelFalImage).toHaveBeenCalledTimes(1);expect(runFalImage).toHaveBeenCalledTimes(1);});
  it("keeps the paid asset, actual receipt and separately applicable stale-head proposal",async()=>{const repository=new MemoryArtboardProposalRepository();const proposal=await persistPaidResultProposal(repository,context,result,{workspace,branchId:"branch",revision:{id:"revision-2",number:2}});expect(proposal.batch.expectedRevisionId).toBe("revision-2");expect(proposal.warnings?.[0]).toMatch(/neu abgeleitet/);expect((proposal.batch.operations[0] as any).layers["generated-intent"].casHash).toBe(hash);expect(await repository.findProposal(proposal.proposalId)).toMatchObject({state:"frozen",receipts:[{payloadFingerprint:expect.stringMatching(/^[a-f0-9]{64}$/),result:{blobHash:hash,costMicrounits:12345,costProvenance:"actual"}}]});});
});
