import { ExternalLink, ShieldQuestion } from 'lucide-react';
import { parseArtifact, type DomainCheck, type PaletteColor } from '../nodes/brand/artifacts';
import { formatDate, useI18n } from '../i18n';

export function BrandArtifactView({ value }: { value: string }) {
  const {t}=useI18n();
  const statusLabel: Record<DomainCheck['status'], Parameters<typeof t>[0]>={registered:'brand.domain.registered', 'not-found':'brand.domain.notFound', unknown:'brand.domain.unknown','rate-limited':'brand.domain.rateLimited',unsupported:'brand.domain.unsupported',invalid:'brand.domain.invalid'};
  let envelope; try { envelope=parseArtifact(value); } catch { return <pre className="brand-json">{value}</pre>; }
  const data=envelope.data as Record<string,unknown>;
  if(envelope.artifact==='flowz.brand-brief') return <div className="brand-summary"><strong>{String(data.brandName||t('brand.unnamed'))}</strong><p>{String(data.offer||'')}</p><small>{String(data.audience||'')}</small></div>;
  if(envelope.artifact==='flowz.audience-analysis') { const insights=['jobs','pains','gains'].flatMap((key)=>Array.isArray(data[key])?data[key] as {statement:string;basis:string}[]:[]);return <div className="brand-summary"><p>{String(data.summary||'')}</p><ul>{insights.slice(0,5).map((item,index)=><li key={index}><span className={`basis ${item.basis}`}>{item.basis==='evidence'?t('brand.evidence'):t('brand.assumption')}</span>{item.statement}</li>)}</ul></div>; }
  if(envelope.artifact==='flowz.name-candidate-list') { const candidates=(data.candidates??[]) as {id:string;name:string;domainSlug:string;rationale:string;trademarkChecked:false}[];return <div className="brand-chip-grid">{candidates.map((item)=><span key={item.id}><strong>{item.name}</strong><small>{item.domainSlug}</small><p>{item.rationale}</p><em>{t('brand.trademarkUnchecked')} · {String(item.trademarkChecked)}</em></span>)}</div>; }
  if(envelope.artifact==='flowz.domain-availability') { const checks=(data.checks??[]) as DomainCheck[];return <div className="domain-grid">{checks.map((item)=><div key={item.domain}><strong>{item.unicodeDomain}</strong><span className={`domain-status ${item.status}`}>{t(statusLabel[item.status])}</span><small>{formatDate(item.checkedAt)}</small></div>)}<p><ShieldQuestion size={12}/>{String(data.disclaimer||'')}</p></div>; }
  if(envelope.artifact==='flowz.handle-plan') { const links=(data.links??[]) as {platform:string;profileUrl:string;validSyntax:boolean}[];return <div className="handle-links">{links.map((item)=><a key={item.platform} href={item.profileUrl} target="_blank" rel="noreferrer">{item.platform}<ExternalLink size={11}/></a>)}<small>{t('brand.manualCheck')}</small></div>; }
  if(envelope.artifact==='flowz.font-pairing') { const heading=data.heading as {family:string;license:string;blobHash?:string;licenseBlobHash?:string};const body=data.body as typeof heading;const id=(font:typeof heading)=>`flowz-${font.blobHash?.slice(0,12)}`;const rules=[heading,body].filter(font=>font.blobHash).map(font=>`@font-face{font-family:${JSON.stringify(id(font))};src:url("flowz-media://localhost/${font.blobHash}") format("truetype");font-display:swap;font-weight:100 900}`).join('');return <div className="font-pair"><style>{rules}</style><strong style={{fontFamily:id(heading)}}>{heading.family}</strong><span style={{fontFamily:id(body)}}>{body.family} · {t('brand.readingSample')}</span><small>{heading.license} · {t('brand.fontProvenance')} · {heading.licenseBlobHash?.slice(0,8)}</small></div>; }
  if(envelope.artifact==='flowz.color-palette') { const colors=(data.colors??[]) as PaletteColor[];const contrast=(data.contrast??[]) as {foreground:string;background:string;ratio:number;aaNormal:boolean;aaLarge:boolean}[];return <div className="palette-preview"><div>{colors.map((color)=><span key={color.role} style={{background:color.hex}} title={`${color.role}: ${color.hex}`}><i>{color.role}</i></span>)}</div><div className="palette-rows">{colors.map(color=><button type="button" key={color.role} onClick={()=>void navigator.clipboard.writeText(color.hex)} title={t('brand.copyHex')}><b style={{background:color.hex}}/><span>{color.role}</span><code>{color.hex}</code></button>)}</div><div className="contrast-rows">{contrast.filter(item=>['text','background','surface'].includes(item.foreground)&&['text','background','surface'].includes(item.background)).map(item=><span key={`${item.foreground}-${item.background}`}>{item.foreground} / {item.background}<b>{item.ratio}:1</b><em>{item.aaNormal?'AA':t('brand.largeOnly')}{item.aaLarge?' ✓':''}</em></span>)}</div><small>{t('brand.aaCombinations',{passing:contrast.filter(item=>item.aaNormal).length,total:contrast.length})}</small></div>; }
  return <pre className="brand-json">{JSON.stringify(data,null,2)}</pre>;
}
