import { BarChart3, Database, LoaderCircle, Trash2, X } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { clearNodeHistory, deleteLibraryResult, deleteProjectAndAssets, loadProjectCosts, loadProjectResults, loadStorageBreakdown, type CostBreakdown, type LibraryResult, type StorageBreakdown } from '../persistence/library';
import { CustomSelect } from './CustomSelect';
import { formatCurrency, formatDate, formatFileSize, localizeErrorMessage, useI18n } from '../i18n';
import { isDesktopRuntime } from '../persistence/projects';

const PAGE_SIZE=20;

type Props={open:boolean;projectId:string;projectName:string;nodeNames:Map<string,string>;protectedResultIds:Set<string>;onClose:()=>void;onChanged:()=>Promise<void>;onProjectDeleted:()=>Promise<void>};
export function DataManagerPalette({open,projectId,projectName,nodeNames,protectedResultIds,onClose,onChanged,onProjectDeleted}:Props){
  const {locale,t}=useI18n();const money=(value:number,provenance?:string)=>`${provenance==='estimated'?t('data.approx'):''}${formatCurrency(value/1_000_000)}`;
  const [tab,setTab]=useState<'storage'|'costs'|'history'>('storage');const [storage,setStorage]=useState<StorageBreakdown>();const [costs,setCosts]=useState<CostBreakdown>();const [history,setHistory]=useState<LibraryResult[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [confirmation,setConfirmation]=useState('');const [query,setQuery]=useState('');const [nodeFilter,setNodeFilter]=useState('all');const [typeFilter,setTypeFilter]=useState('all');const [page,setPage]=useState(0);const generation=useRef(0);
  const reload=async()=>{const run=++generation.current;if(!isDesktopRuntime()){setStorage(undefined);setCosts(undefined);setHistory([]);setBusy(false);setError(t('data.desktopOnly'));return}setBusy(true);setError('');try{const [s,c,h]=await Promise.all([loadStorageBreakdown(),loadProjectCosts(projectId),loadProjectResults(projectId)]);if(run!==generation.current)return;setStorage(s);setCosts(c);setHistory(h)}catch(reason){if(run===generation.current)setError(reason instanceof Error?reason.message:String(reason))}finally{if(run===generation.current)setBusy(false)}};
  useEffect(()=>{if(open)void reload();return()=>{generation.current+=1}},[open,projectId]);
  useEffect(()=>setPage(0),[tab,query,nodeFilter,typeFilter]);
  const nodeRows=useMemo(()=>Array.from(new Set(history.map(item=>item.nodeId))).filter(Boolean),[history]);
  const options=[{value:'all',label:t('data.allNodes')},...nodeRows.map(value=>({value,label:nodeNames.get(value)??value.slice(0,8)}))];
  const normalized=query.trim().toLocaleLowerCase(locale);
  const storageRows=(storage?.projects??[]).filter(row=>row.projectId===projectId&&(nodeFilter==='all'||row.nodeId===nodeFilter)&&(typeFilter==='all'||row.mediaType===typeFilter)&&(!normalized||`${nodeNames.get(row.nodeId)??''} ${row.mediaType}`.toLocaleLowerCase(locale).includes(normalized)));
  const costRows=(costs?.rows??[]).filter(row=>(nodeFilter==='all'||row.nodeId===nodeFilter)&&(!normalized||`${nodeNames.get(row.nodeId)??''} ${row.model} ${row.day}`.toLocaleLowerCase(locale).includes(normalized)));
  const historyRows=history.filter(item=>(nodeFilter==='all'||item.nodeId===nodeFilter)&&(typeFilter==='all'||item.kind===typeFilter)&&(!normalized||`${nodeNames.get(item.nodeId)??''} ${item.kind} ${item.model??''}`.toLocaleLowerCase(locale).includes(normalized)));
  const rows=tab==='storage'?storageRows:tab==='costs'?costRows:historyRows;const pages=Math.max(1,Math.ceil(rows.length/PAGE_SIZE));const visible=rows.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE);
  if(!open)return null;
  const protectedList=()=>Array.from(protectedResultIds);
  const removeResult=async(item:LibraryResult)=>{if(item.active||protectedResultIds.has(item.resultId)||!confirm(t('data.deleteVariantConfirm')))return;setBusy(true);try{await deleteLibraryResult(projectId,item.resultId,protectedList());await onChanged();await reload()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};
  const clearNode=async(nodeId:string)=>{if(!confirm(t('data.clearNodeConfirm',{name:nodeNames.get(nodeId)??nodeId})))return;setBusy(true);try{await clearNodeHistory(projectId,nodeId,protectedList());await onChanged();await reload()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};
  return <section className="data-manager" aria-label={t('data.title')}><header><Database size={14}/><strong>{t('canvas.storage')}</strong>{busy&&<LoaderCircle className="spin" size={13}/>}<button className="icon-button" onClick={onClose} aria-label={t('common.close')}><X size={14}/></button></header>
    <nav role="tablist" aria-label={t('data.title')}>{(['storage','costs','history'] as const).map(value=><button role="tab" aria-selected={tab===value} key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{value==='storage'?t('data.storage'):value==='costs'?t('data.costs'):t('data.history')}</button>)}</nav>
    <div className="data-manager-filters"><input aria-label={t('common.search')} value={query} onChange={event=>setQuery(event.target.value)} placeholder={t('common.search')}/><CustomSelect label={t('data.filterNode')} searchable value={nodeFilter} options={options} onChange={setNodeFilter}/>{tab!=='costs'&&<CustomSelect label={t('data.filterType')} value={typeFilter} options={[{value:'all',label:t('data.allTypes')},...Array.from(new Set((tab==='storage'?storageRows.map(row=>row.mediaType):history.map(item=>item.kind)))).map(value=>({value,label:value}))]} onChange={setTypeFilter}/>}</div>
    <div className="data-manager-body nowheel nopan" role="tabpanel" onWheelCapture={event=>event.stopPropagation()}>{error&&<div className="node-error" role="alert">{localizeErrorMessage(error)}</div>}
      {tab==='storage'&&storage&&<><div className="data-total"><strong>{formatFileSize(storage.totalBytes)}</strong><span>{storage.totalBlobs} {t('data.files')}</span></div><p className="data-honesty">{t('data.storageHonesty')}</p><div className="data-rows">{(visible as typeof storageRows).map((row,index)=><div key={`${row.nodeId}-${row.mediaType}-${index}`}><span>{nodeNames.get(row.nodeId)??t('data.removedNode')} · {row.mediaType}</span><strong>{formatFileSize(row.referencedBytes)}</strong><small>{row.resultCount} {t('data.resultsSize')}</small></div>)}</div><div className="danger-zone"><strong>{t('data.deleteProject')}</strong><span>{t('data.preserveGlobal')}</span><input value={confirmation} onChange={event=>setConfirmation(event.target.value)} placeholder={t('data.enterProject',{name:projectName})}/><button className="secondary danger" disabled={confirmation!==projectName||busy} onClick={()=>void deleteProjectAndAssets(projectId,confirmation).then(onProjectDeleted).catch(reason=>setError(String(reason)))}><Trash2 size={12}/>{t('document.deletePermanent')}</button></div></>}
      {tab==='costs'&&costs&&<><div className="cost-summary"><div><strong>{money(costs.actualMicrounits)}</strong><span>{t('data.actual')}</span></div><div><strong>{money(costs.estimatedMicrounits,'estimated')}</strong><span>{t('data.estimated')}</span></div><div><strong>{costs.unknownRuns}</strong><span>{t('data.unknown')}</span></div></div><p className="data-honesty">{t('data.costHonesty')}</p><div className="data-rows">{(visible as typeof costRows).map((row,index)=><div key={`${row.nodeId}-${row.model}-${row.day}-${index}`}><span>{nodeNames.get(row.nodeId)??t('data.removedNode')} · {row.model}</span><strong>{row.amountMicrounits==null?t('data.unknown'):money(row.amountMicrounits,row.provenance)}</strong><small>{row.day} · {row.provenance==='actual'?t('data.actual'):row.provenance==='estimated'?t('data.estimated'):t('data.unknown')} · {t('data.runs',{count:row.runs})}</small></div>)}</div></>}
      {tab==='history'&&<><div className="history-node-actions">{nodeRows.map(nodeId=><button key={nodeId} className="secondary" onClick={()=>void clearNode(nodeId)}>{t('data.oldHistory')} · {nodeNames.get(nodeId)??nodeId.slice(0,8)}</button>)}</div><div className="data-rows">{(visible as typeof historyRows).map(item=>{const provenance=String(item.parameters?.costProvenance??'actual');return <div key={item.resultId}><span>{nodeNames.get(item.nodeId)??t('data.removedNode')} · {item.kind}</span><strong>{item.active?t('data.active'):formatDate(item.createdAt,{dateStyle:'medium'})}</strong><small>{item.model??t('canvas.local')}{item.costMicrounits!=null?` · ${money(item.costMicrounits,provenance)}`:provenance==='unknown'?` · ${t('data.costUnknown')}`:''}</small><button className="icon-button danger" aria-label={t('data.deleteVariant',{name:nodeNames.get(item.nodeId)??'Node'})} disabled={item.active||protectedResultIds.has(item.resultId)||busy} title={item.active?t('data.activateOther'):protectedResultIds.has(item.resultId)?t('data.referenced'):t('home.delete')} onClick={()=>void removeResult(item)}><Trash2 size={12}/></button></div>})}</div></>}
    </div><div className="data-pagination"><button className="secondary" disabled={page===0} onClick={()=>setPage(value=>value-1)}>{t('data.previous')}</button><span>{page+1} / {pages}</span><button className="secondary" disabled={page+1>=pages} onClick={()=>setPage(value=>value+1)}>{t('data.next')}</button></div><footer><BarChart3 size={11}/>{t('data.noAutoDelete')}</footer>
  </section>;
}
