import { describe, expect, it } from "vitest";
import { ARTBOARD_FORMATS, duplicateBoard, findBoardPlacement, resolveUpstreamUpdate, serializeFlowzArtboard, validateArtboardDocument, validateArtboardWorkspace, workspaceOutputs, type ArtboardBoard, type ArtboardDocument, type ArtboardWorkspace } from "./artboard-domain";

const now = "2026-07-12T10:00:00.000Z";
const document = (id = "document-1", childIds: string[] = ["text-1"]): ArtboardDocument => ({schemaVersion:1,id,name:"Post",format:{preset:"instagram-post",width:ARTBOARD_FORMATS["instagram-post"].width,height:ARTBOARD_FORMATS["instagram-post"].height},paint:{kind:"solid",color:"#101010"},rootLayerIds:["group-1"],layers:{"group-1":{id:"group-1",type:"group",name:"Inhalt",locked:false,visible:true,version:1,geometry:{x:0,y:0,width:1080,height:1080,rotation:0},childIds},"text-1":{id:"text-1",type:"text",name:"Titel",locked:false,visible:true,version:1,geometry:{x:80,y:80,width:920,height:240,rotation:0},text:"Hallo Welt",color:"#FFFFFF",fontSize:96,align:"left"}},bindings:{},tokenRefs:{}});
const board = (id = "board-1"): ArtboardBoard => ({id,name:"Post",activeRevisionId:`revision-${id}`,document:document(`document-${id}`),inputSnapshot:{id:`snapshot-${id}`,createdAt:now,bindings:{}},ancestry:{branchId:"branch-main"},createdAt:now});
const workspace = (): ArtboardWorkspace => ({schemaVersion:1,id:"workspace-1",name:"Kampagne",boards:{"board-1":board()},placements:{"board-1":{x:64,y:64}},selectedBoardIds:["board-1"],activeBoardId:"board-1",pasteboard:{margin:64,gap:64,grid:8}});

describe("ArtboardDocument",()=>{
  it("validates the canonical document and rejects unknown fields",()=>{const value=document();expect(()=>validateArtboardDocument(value)).not.toThrow();expect(()=>validateArtboardDocument({...value,html:"<b>legacy</b>"})).toThrow(/unbekannte Felder/);});
  it("rejects URLs, CSS/code, invalid bounds, cycles and excessive depth",()=>{const url=document();(url.layers["text-1"] as any).text="https://example.test";expect(()=>validateArtboardDocument(url)).toThrow(/URL, CSS/);const bounds=document();bounds.layers["text-1"].geometry.x=1000;expect(()=>validateArtboardDocument(bounds)).toThrow(/außerhalb/);const cycle=document("cycle",["group-1"]);delete cycle.layers["text-1"];expect(()=>validateArtboardDocument(cycle)).toThrow(/zyklus/i);const deep=document();delete deep.layers["text-1"];deep.rootLayerIds=["g1"];for(let i=1;i<=7;i++)deep.layers[`g${i}`]={id:`g${i}`,type:"group",name:`G${i}`,locked:false,visible:true,version:1,geometry:{x:0,y:0,width:10,height:10,rotation:0},childIds:i===7?[]:[`g${i+1}`]};delete deep.layers["group-1"];expect(()=>validateArtboardDocument(deep)).toThrow(/Ebenentiefe/);});
});

describe("ArtboardWorkspace",()=>{
  it("places duplicates deterministically to the right without overlap and preserves the source",()=>{const original=workspace();const a=duplicateBoard(original,"board-1",{boardId:"board-2",documentId:"document-2",snapshotId:"snapshot-2"},now);const b=duplicateBoard(original,"board-1",{boardId:"board-2",documentId:"document-2",snapshotId:"snapshot-2"},now);expect(a.placements["board-2"]).toEqual({x:1208,y:64});expect(a.placements).toEqual(b.placements);expect(a.boards["board-1"]).toEqual(original.boards["board-1"]);expect(a.boards["board-2"].ancestry).toMatchObject({parentBoardId:"board-1",sourceRevisionId:original.boards["board-1"].activeRevisionId});expect(()=>validateArtboardWorkspace(a)).not.toThrow();});
  it("falls back to the next row for mixed formats",()=>{let value=workspace();value=duplicateBoard(value,"board-1",{boardId:"board-2",documentId:"document-2",snapshotId:"snapshot-2"},now);const placement=findBoardPlacement(value,{preset:"instagram-story",width:ARTBOARD_FORMATS["instagram-story"].width,height:ARTBOARD_FORMATS["instagram-story"].height},"board-1");expect(placement.y).toBeGreaterThan(64);});
  it("rejects collisions",()=>{const value=workspace();value.boards["board-2"]=board("board-2");value.placements["board-2"]={x:100,y:100};expect(()=>validateArtboardWorkspace(value)).toThrow(/überlappen/);});
  it("keeps the active scalar separate from the deliberately selected list",()=>{const value=duplicateBoard(workspace(),"board-1",{boardId:"board-2",documentId:"document-2",snapshotId:"snapshot-2"},now);value.selectedBoardIds=["board-1","board-2"];expect(workspaceOutputs(value,{"board-1":"image-a","board-2":"image-b"})).toMatchObject({activeBoard:{id:"board-2"},image:"image-b",selectedImages:["image-a","image-b"]});value.selectedBoardIds=[];expect(workspaceOutputs(value,{"board-1":"image-a","board-2":"image-b"}).selectedImages).toEqual([]);});
  it("never applies a new upstream version without a deliberate decision",()=>{const update={state:"new-version-available" as const,boardId:"board-1",currentSnapshotId:"snapshot-board-1",availableSnapshot:{id:"snapshot-new",createdAt:now,bindings:{}}};expect(resolveUpstreamUpdate(update,"keep-current")).toEqual({type:"none",boardId:"board-1"});expect(resolveUpstreamUpdate(update,"update-current-board")).toMatchObject({type:"create-revision",boardId:"board-1"});expect(resolveUpstreamUpdate(update,"create-new-variant")).toMatchObject({type:"create-board-variant",sourceBoardId:"board-1"});});
  it("serializes .flowz-artboard manifests deterministically",()=>{const a=workspace();const b={...a,placements:{...a.placements},boards:{...a.boards}};expect(serializeFlowzArtboard(a)).toBe(serializeFlowzArtboard(b));expect(serializeFlowzArtboard(a)).toContain('"format":"flowz-artboard"');});
});
